/**
 * Script to extract text from CV PDF files automatically
 * This runs before dev/build to generate cv-content.txt
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PDF_PATHS = [
    'public/documents/english/EN - Muammar Mufid - Resume 0812b.pdf',
    'public/documents/indonesia/Muammar Mufid - Resume 0812b-1.pdf',
];

const OUTPUT_PATH = 'public/cv-content.txt';

async function extractPdfText(pdfPath) {
    try {
        const absolutePath = path.resolve(__dirname, '..', pdfPath);

        if (!fs.existsSync(absolutePath)) {
            console.warn(`⚠️  PDF not found: ${pdfPath}`);
            return null;
        }

        // Dynamic import pdfjs-dist
        const pdfjsLib = await import('pdfjs-dist/legacy/build/pdf.mjs');

        // Read PDF file
        const dataBuffer = fs.readFileSync(absolutePath);
        const uint8Array = new Uint8Array(dataBuffer);

        // Load PDF document
        const loadingTask = pdfjsLib.getDocument({ data: uint8Array });
        const pdf = await loadingTask.promise;

        let fullText = '';

        // Extract text from each page
        for (let i = 1; i <= pdf.numPages; i++) {
            const page = await pdf.getPage(i);
            const textContent = await page.getTextContent();
            const pageText = textContent.items
                .map(item => ('str' in item ? item.str : ''))
                .join(' ');
            fullText += pageText + '\n';
        }

        return {
            path: pdfPath,
            text: fullText,
            numPages: pdf.numPages,
        };
    } catch (error) {
        console.error(`❌ Error extracting ${pdfPath}:`, error.message);
        return null;
    }
}

async function main() {
    console.log('📄 Extracting CV content from PDFs...\n');

    const results = [];

    for (const pdfPath of PDF_PATHS) {
        console.log(`  Processing: ${pdfPath}`);
        const result = await extractPdfText(pdfPath);
        if (result) {
            results.push(result);
            console.log(`  ✅ Extracted ${result.numPages} page(s)`);
        }
    }

    if (results.length === 0) {
        console.error('\n❌ No PDFs could be extracted!');
        process.exit(1);
    }

    // Combine all extracted text with language labels
    let combinedContent = `# CV CONTENT - AUTO-GENERATED FROM PDF
# Generated at: ${new Date().toISOString()}
# DO NOT EDIT THIS FILE MANUALLY - It will be overwritten
# To update, modify the PDF files in public/documents/

`;

    for (const result of results) {
        const lang = result.path.includes('/english/') ? 'ENGLISH' : 'INDONESIA';
        combinedContent += `\n${'='.repeat(60)}\n`;
        combinedContent += `CV VERSION: ${lang}\n`;
        combinedContent += `Source: ${result.path}\n`;
        combinedContent += `${'='.repeat(60)}\n\n`;
        combinedContent += result.text.trim();
        combinedContent += '\n';
    }

    // Write to output file
    const outputPath = path.resolve(__dirname, '..', OUTPUT_PATH);
    fs.writeFileSync(outputPath, combinedContent, 'utf-8');

    console.log(`\n✅ CV content extracted to: ${OUTPUT_PATH}`);
    console.log(`   Total sources: ${results.length}`);
}

main().catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
});
