name: Deploy Portofolio Next.js to Cloudflare Pages

on:
  push:
    branches:
      - main # Ini akan memicu workflow setiap push ke branch 'main'
  workflow_dispatch: # Memungkinkan Anda memicu deployment secara manual dari GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write # Izin yang diperlukan untuk deployment Pages
    name: Deploy to Cloudflare Pages
    environment: production # Opsional: Mengaitkan dengan environment GitHub, baik untuk visibility maupun secret management

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Mengambil kode dari repositori GitHub

      # --- PERUBAHAN DI SINI: Menghapus pnpm/action-setup karena kita menggunakan npm. ---
      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Mengatur lingkungan Node.js
        with:
          node-version: '20' # Pastikan versi ini sesuai dengan v20.19.2 Anda (v20)
          cache: 'npm' # Mengaktifkan caching untuk npm dependencies, mencari package-lock.json

      - name: Install Dependencies
        run: npm install # Menginstal semua dependensi proyek Anda menggunakan npm

      # Menjalankan skrip 'pages:build' dari package.json Anda
      # Ini akan menjalankan 'npx @cloudflare/next-on-pages'
      # dan menghasilkan output yang siap deploy di `.vercel/output/`
      - name: Build Next.js Project for Cloudflare Pages
        run: npm run pages:build # Menjalankan skrip 'pages:build' menggunakan npm
        env:
          NODE_ENV: production

      # Langkah Deploy menggunakan cloudflare/wrangler-action
      # Ini akan mengambil output dari langkah build sebelumnya (`.vercel/output/`)
      # dan mendeploy-nya ke Cloudflare Pages.
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Direktori output dari `npx @cloudflare/next-on-pages` adalah `.vercel/output/`
          command: 'pages deploy .vercel/output --project-name muammar --branch main'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
